### ISSUE TITLE
How to not show dotfiles

### ISSUE THREAD

**Issue by RaoniSilvestre** [pls-rs/pls#101]
I was looking for how i could use pls to only show files/directories that doesn't starts with dot, i was trying with
-e '\.*'
but it also excludes for example test.rs from the showed list.

I think would be cool for this project have some boolean flag to decide if it shows or not the dotfiles.

**Comment by dhruvkb** [comment]
By default, `pls` shows dotfiles because even though they are usually considered "hidden", most of them are actually very relevant for developers. For example, see `.gitignore`, `.editorconfig`, `.pls.yml` and `.rustfmt.toml` in this project's root.

There are two ways to remove `.dotfiles` from showing up.

1. Exclude using regex

   You were on the right track except for a small issue with the regex. You need to use caret `^` to signify the dot at the start of the file name.

   <img width="218" alt="Screenshot 2024-05-11 at 6 44 54 PM" src="https://github.com/pls-rs/pls/assets/16580576/95491a4f-a2ee-4b4e-b452-4829830ff740">

2. Exclude using spec

   You can also define a spec for the pattern `^\.` that sets the importance to a large negative number. This will also prevent the dotfiles from being listed.

   ```yaml
   # .pls.yml
   specs:
     - pattern: ^\.
       importance: -10
   ```

**Comment by RaoniSilvestre** [comment]
In my case im using some aliases on my .zshrc, so i think i'll stick with the first option.

Thank you for the explanation! :smile:
